import type { TalentCardProps } from "@/app/components/talent/TalentCard";

export type ServiceTalent = TalentCardProps & {
  serviceSlugs: string[];
};

export const serviceTalents: ServiceTalent[] = [
  {
    name: "Tunde Folayan",
    role: "Content Strategist & Copywriter",
    status: "online",
    price: "$25/hr",
    image: "/tweg.jpg",
    rating: 4.8,
    reviews: 210,
    location: "Ibadan, NG",
    bio: "Helping brands tell their stories through compelling copy. Experienced in B2B SaaS marketing and long-form SEO content.",
    tags: ["Copywriting", "SEO", "Blogging"],
    verified: true,
    serviceSlugs: ["content-writing", "copywriting"],
  },
  {
    name: "Halima Musa",
    role: "SEO Content Writer",
    status: "online",
    price: "$18/hr",
    image: "/tweg.jpg",
    rating: 4.6,
    reviews: 88,
    location: "Kano, NG",
    bio: "Writes SEO-first articles that rank and convert. Comfortable with briefs, research, and editorial style guides.",
    tags: ["SEO", "Content", "Editing"],
    verified: true,
    serviceSlugs: ["content-writing", "editing-proofreading"],
  },
  {
    name: "Adaeze Obi",
    role: "Editor & Proofreader",
    status: "away",
    price: "$22/hr",
    image: "/tweg.jpg",
    rating: 4.9,
    reviews: 142,
    location: "Enugu, NG",
    bio: "Copyediting, proofreading, and tone polishing for marketing pages, blog posts, and reports.",
    tags: ["Proofreading", "Copyediting", "Style Guides"],
    verified: true,
    serviceSlugs: ["editing-proofreading", "copywriting"],
  },
  {
    name: "Chidi Okoro",
    role: "Senior Fullstack Developer",
    status: "online",
    price: "$45/hr",
    image: "/tweg.jpg",
    rating: 4.9,
    reviews: 124,
    location: "Lagos, NG",
    bio: "Over 8 years building scalable SaaS apps using React, Node.js, and AWS. Strong architecture and performance focus.",
    tags: ["React", "Node.js", "PostgreSQL", "AWS"],
    verified: true,
    serviceSlugs: ["web-development"],
  },
  {
    name: "Ngozi Eze",
    role: "Frontend Developer",
    status: "online",
    price: "$28/hr",
    image: "/tweg.jpg",
    rating: 4.7,
    reviews: 64,
    location: "Enugu, NG",
    bio: "Builds fast, accessible interfaces with React and Tailwind. Comfortable collaborating with design and backend.",
    tags: ["React", "Tailwind", "TypeScript"],
    verified: true,
    serviceSlugs: ["web-development"],
  },
  {
    name: "Amina Yusuf",
    role: "UI/UX Designer",
    status: "away",
    price: "$35/hr",
    image: "/tweg.jpg",
    rating: 5.0,
    reviews: 98,
    location: "Abuja, NG",
    bio: "User-centered designer specializing in mobile app UX, prototypes, and scalable design systems.",
    tags: ["Figma", "Prototyping", "UX Research"],
    verified: true,
    serviceSlugs: ["ui-ux-design"],
  },
  {
    name: "Seyi Adekunle",
    role: "Product Designer",
    status: "online",
    price: "$40/hr",
    image: "/tweg.jpg",
    rating: 4.6,
    reviews: 42,
    location: "Lagos, NG",
    bio: "Designs clean flows and UI for SaaS products. Strong discovery, wireframes, and handoff.",
    tags: ["Product Design", "Figma", "Design Systems"],
    verified: true,
    serviceSlugs: ["ui-ux-design"],
  },
  {
    name: "Grace Adebayo",
    role: "Digital Marketing Specialist",
    status: "online",
    price: "$30/hr",
    image: "/tweg.jpg",
    rating: 4.9,
    reviews: 156,
    location: "Port Harcourt, NG",
    bio: "Strategic marketer focused on ROI. Expert in Google Ads, Meta ads, and analytics-driven growth.",
    tags: ["Google Ads", "PPC", "Growth"],
    verified: true,
    serviceSlugs: ["digital-marketing"],
  },
  {
    name: "Femi Okafor",
    role: "Performance Marketer",
    status: "offline",
    price: "$55/hr",
    image: "/tweg.jpg",
    rating: 4.9,
    reviews: 132,
    location: "Benin City, NG",
    bio: "Runs data-driven campaigns across Google and Meta. Strong tracking, creative testing, and CRO.",
    tags: ["Meta Ads", "Google Ads", "Analytics"],
    verified: true,
    serviceSlugs: ["digital-marketing"],
  },
  {
    name: "Ifeanyi Nwosu",
    role: "Data Analyst",
    status: "online",
    price: "$32/hr",
    image: "/tweg.jpg",
    rating: 4.8,
    reviews: 76,
    location: "Lagos, NG",
    bio: "Builds dashboards and reports for growth teams. Comfortable with SQL, spreadsheets, and stakeholder-ready insights.",
    tags: ["SQL", "Power BI", "Reporting"],
    verified: true,
    serviceSlugs: ["data-analytics"],
  },
  {
    name: "Ruth Danladi",
    role: "BI & Analytics Specialist",
    status: "away",
    price: "$38/hr",
    image: "/tweg.jpg",
    rating: 4.7,
    reviews: 61,
    location: "Abuja, NG",
    bio: "Transforms messy data into clear dashboards. Strong in KPI definition, automation, and business storytelling.",
    tags: ["Dashboards", "KPIs", "Data Modeling"],
    verified: true,
    serviceSlugs: ["data-analytics"],
  },
  {
    name: "Zainab Bello",
    role: "Virtual Assistant",
    status: "online",
    price: "$16/hr",
    image: "/tweg.jpg",
    rating: 4.9,
    reviews: 189,
    location: "Kano, NG",
    bio: "Keeps operations running smoothly: inbox, scheduling, research, documentation, and client follow-ups.",
    tags: ["Admin Support", "Scheduling", "Research"],
    verified: true,
    serviceSlugs: ["virtual-assistance"],
  },
  {
    name: "Samuel Ajayi",
    role: "Executive Assistant",
    status: "offline",
    price: "$20/hr",
    image: "/tweg.jpg",
    rating: 4.6,
    reviews: 103,
    location: "Ibadan, NG",
    bio: "Executive support for founders: calendar management, travel planning, vendor coordination, and SOPs.",
    tags: ["Operations", "Calendar", "Documentation"],
    verified: true,
    serviceSlugs: ["virtual-assistance"],
  },
];

export function getTalentsForService(slug: string) {
  return serviceTalents.filter((t) => t.serviceSlugs.includes(slug));
}
